apiVersion: v1
kind: Service
metadata:
  name: ftps-alpine
  labels:
    run: ftps-alpine
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 21
    targetPort: 21
  selector:
    run: ftps
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-alpine
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      run: ftps
  replicas: 1
  template:
    metadata:
      labels:
        run: ftps
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: ftpssecret
      - name: configmap-volume
        configMap:
          name: ftpsconfigmap
      containers:
      - name: ftps
        image: test_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 21
#        volumeMounts:
#        - mountPath: /etc/ssl/private
#          name: secret-volume
#        - mountPath: /etc/vsftpd
#          name: configmap-volume
