apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mysql-pass
  literals:
  - password=password

resources:
- nginx.yaml
- ftps.yaml
- mysql-deployment.yaml
- wordpress-deployment.yaml
- phpmyadmin.yaml
- influxdb.yaml
- grafana.yaml
- telegraf.yaml
