FROM alpine:3.11.3

RUN apk update && apk upgrade --available

RUN apk add --no-cache openrc

RUN apk add openssl && apk add vim && apk add nginx

RUN mkdir /run/nginx && touch /run/nginx/nginx.pid

ADD start.sh /start.sh

RUN chmod 755 start.sh

ENTRYPOINT ["sh", "/start.sh"]
