apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30505
  selector:
    run: wordpress
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      run: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        run: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_alpine
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        - containerPort: 30505
